import os
import sys

sys.stdout.reconfigure(encoding='utf-8')

locales = {
    'de': {
        'sourceGameLabel': 'Aktuelles Spiel',
        'targetGameLabel': 'Zielspiel',
        'sourceDpiLabel': 'Aktuelle DPI',
        'targetDpiLabel': 'Ziel-DPI',
        'sensitivityLabel': 'Empfindlichkeit im Spiel',
        'linkDpiLabel': 'Gleiche DPI beibehalten',
        'sourceStationLabel': 'Aktuelles Setup',
        'targetStationLabel': 'Ziel-Setup',
        'guideSourceText': 'Wähle dein Spiel, gib deine DPI und deine horizontale Empfindlichkeit ein.',
        'guideTargetText': 'Wähle das Zielspiel. Lasse DPI verknüpft, außer du änderst sie.',
        'guideResultText': 'Kopiere das Ergebnis in das Zielspiel und überprüfe eine 360-Grad-Drehung.',
        'sourceInputHint': 'Finde diese Werte in deiner Maus-Software und den Spieleinstellungen.',
        'targetInputHint': 'Der Zielwert erscheint unten, sobald die Eingaben gültig sind.',
        'profileResetText': 'Empfindlichkeit auf Beispielwert zurückgesetzt. Ersetze ihn durch deinen Wert.',
        'resultForGameTemplate': '3. Gib diesen Wert in {game} ein',
        'yawLabel': 'Yaw-Skala',
        'measuredProfileLabel': 'Gemessenes Profil',
        'documentedProfileLabel': 'Dokumentiertes Profil',
        'targetSensitivityLabel': 'Gib diese Empfindlichkeit ein',
        'copyResultLabel': 'Ergebnis kopieren',
        'copiedLabel': 'Kopiert',
        'swapLabel': 'Umrechnung umkehren',
        'swapButtonLabel': 'Tauschen',
        'shareLabel': 'Link kopieren',
        'shareCopiedLabel': 'Link kopiert',
        'presetsLabel': 'Voreinstellungen',
        'presetFastLabel': 'Schnell 22 cm',
        'presetBalancedLabel': 'Ausgewogen 34 cm',
        'presetControlLabel': 'Kontrolle 50 cm',
        'cmUnitLabel': 'Metrisch',
        'inchUnitLabel': 'Imperial',
        'physicalArcLabel': 'Eine volle Drehung',
        'sourceEdpiLabel': 'Quell-eDPI',
        'targetEdpiLabel': 'Ziel-eDPI',
        'countsLabel': 'Mausimpulse',
        'matchQualityLabel': 'Profilgenauigkeit',
        'exactMathLabel': 'Exakter Yaw-Wert',
        'calibrationLabel': 'Physische Prüfung empfohlen',
        'fastBandLabel': 'Schnelle Orbit-Zone',
        'balancedBandLabel': 'Ausgewogene Orbit-Zone',
        'controlBandLabel': 'Kontroll-Orbit-Zone',
        'extendedBandLabel': 'Erweiterte Orbit-Zone',
        'formulaLabel': 'Umrechnungsformel',
        'formulaText': 'Ziel-Empfindlichkeit = Quell-Empfindlichkeit x Quell-DPI x Quell-Yaw / (Ziel-DPI x Ziel-Yaw)',
        'verificationTitle': 'Kalibrierung abschließen',
        'verificationText': 'Markiere einen Startpunkt auf deinem Mauspad und führe in beiden Spielen eine 360-Grad-Drehung aus.',
        'baseAimOnlyText': 'Nur für Basis-Hipfire horizontal.',
        'invalidInputText': 'Gib positive Werte ein.',
        'openGameMenuLabel': 'Spielprofil-Menü öffnen'
    },
    'fr': {
        'sourceGameLabel': 'Jeu actuel',
        'targetGameLabel': 'Jeu cible',
        'sourceDpiLabel': 'DPI actuel',
        'targetDpiLabel': 'DPI cible',
        'sensitivityLabel': 'Sensibilité affichée dans le jeu',
        'linkDpiLabel': 'Conserver le même DPI',
        'sourceStationLabel': 'Configuration actuelle',
        'targetStationLabel': 'Configuration cible',
        'guideSourceText': 'Choisissez votre jeu actuel, puis entrez le DPI et la sensibilité horizontale.',
        'guideTargetText': 'Choisissez le jeu cible. Laissez le DPI lié sauf si vous le modifiez.',
        'guideResultText': 'Copiez le résultat dans le jeu cible, puis vérifiez un tour complet.',
        'sourceInputHint': 'Trouvez ces valeurs dans le logiciel de votre souris et les réglages du jeu.',
        'targetInputHint': 'La valeur cible apparaît ci-dessous dès que la saisie est valide.',
        'profileResetText': 'Sensibilité réinitialisée sur un exemple. Remplacez-la par votre valeur.',
        'resultForGameTemplate': '3. Entrez cette valeur dans {game}',
        'yawLabel': 'Échelle yaw',
        'measuredProfileLabel': 'Profil mesuré',
        'documentedProfileLabel': 'Profil officiel',
        'targetSensitivityLabel': 'Entrez cette sensibilité',
        'copyResultLabel': 'Copier le résultat',
        'copiedLabel': 'Copié',
        'swapLabel': 'Inverser la conversion',
        'swapButtonLabel': 'Échanger',
        'shareLabel': 'Copier le lien',
        'shareCopiedLabel': 'Lien copié',
        'presetsLabel': 'Préréglages physiques',
        'presetFastLabel': 'Rapide 22 cm',
        'presetBalancedLabel': 'Équilibré 34 cm',
        'presetControlLabel': 'Contrôle 50 cm',
        'cmUnitLabel': 'Métrique',
        'inchUnitLabel': 'Impérial',
        'physicalArcLabel': 'Un tour complet',
        'sourceEdpiLabel': 'eDPI source',
        'targetEdpiLabel': 'eDPI cible',
        'countsLabel': 'Impulsions souris',
        'matchQualityLabel': 'Confiance du profil',
        'exactMathLabel': 'Correspondance yaw exacte',
        'calibrationLabel': 'Vérification physique recommandée',
        'fastBandLabel': 'Zone rapide',
        'balancedBandLabel': 'Zone équilibrée',
        'controlBandLabel': 'Zone contrôle',
        'extendedBandLabel': 'Zone étendue',
        'formulaLabel': 'Formule de conversion',
        'formulaText': 'sensibilité cible = sensibilité source x DPI source x yaw source / (DPI cible x yaw cible)',
        'verificationTitle': 'Finaliser l étalonnage',
        'verificationText': 'Marquez un point de départ sur votre tapis et effectuez un tour de 360 degrés dans les deux jeux.',
        'baseAimOnlyText': 'Tir depuis la hanche uniquement.',
        'invalidInputText': 'Entrez des valeurs positives.',
        'openGameMenuLabel': 'Ouvrir le menu des profils de jeu'
    },
    'it': {
        'sourceGameLabel': 'Gioco attuale',
        'targetGameLabel': 'Gioco di destinazione',
        'sourceDpiLabel': 'DPI attuale',
        'targetDpiLabel': 'DPI di destinazione',
        'sensitivityLabel': 'Sensibilità mostrata nel gioco',
        'linkDpiLabel': 'Mantenere lo stesso DPI',
        'sourceStationLabel': 'Configurazione attuale',
        'targetStationLabel': 'Configurazione di destinazione',
        'guideSourceText': 'Scegli il gioco attuale, poi inserisci DPI e sensibilità orizzontale.',
        'guideTargetText': 'Scegli il gioco di destinazione. Lascia il DPI collegato se non lo modifichi.',
        'guideResultText': 'Copia il risultato nel nuovo gioco e verifica una rotazione di 360 gradi.',
        'sourceInputHint': 'Trova questi valori nel software del mouse e nelle impostazioni di gioco.',
        'targetInputHint': 'Il valore di destinazione appare qui sotto non appena la configurazione è valida.',
        'profileResetText': 'Sensibilità ripristinata su un esempio base. Sostituiscila con il tuo valore reale.',
        'resultForGameTemplate': '3. Inserisci questo valore in {game}',
        'yawLabel': 'Scala yaw',
        'measuredProfileLabel': 'Profilo misurato',
        'documentedProfileLabel': 'Profilo ufficiale',
        'targetSensitivityLabel': 'Inserisci questa sensibilità',
        'copyResultLabel': 'Copia risultato',
        'copiedLabel': 'Copiato',
        'swapLabel': 'Inverti conversione',
        'swapButtonLabel': 'Scambia',
        'shareLabel': 'Copia link',
        'shareCopiedLabel': 'Link copiato',
        'presetsLabel': 'Preimpostazioni di mirino',
        'presetFastLabel': 'Veloce 22 cm',
        'presetBalancedLabel': 'Bilanciato 34 cm',
        'presetControlLabel': 'Controllo 50 cm',
        'cmUnitLabel': 'Metrico',
        'inchUnitLabel': 'Imperiale',
        'physicalArcLabel': 'Giro completo a 360 gradi',
        'sourceEdpiLabel': 'eDPI di origine',
        'targetEdpiLabel': 'eDPI di destinazione',
        'countsLabel': 'Impulsi del mouse',
        'matchQualityLabel': 'Affidabilità del profilo',
        'exactMathLabel': 'Valore yaw ufficiale',
        'calibrationLabel': 'Verifica fisica consigliata',
        'fastBandLabel': 'Zona veloce',
        'balancedBandLabel': 'Zona bilanciata',
        'controlBandLabel': 'Zona di controllo',
        'extendedBandLabel': 'Zona estesa',
        'formulaLabel': 'Formula di conversione',
        'formulaText': 'sensibilità destinazione = sensibilità origine x DPI origine x yaw origine / (DPI destinazione x yaw destinazione)',
        'verificationTitle': 'Verifica su tappetino',
        'verificationText': 'Segna un punto di partenza sul tappetino ed esegui un giro a 360 gradi in entrambi i giochi.',
        'baseAimOnlyText': 'Esclusivamente per tiro dalla cintola (hipfire).',
        'invalidInputText': 'Inserisci valori positivi.',
        'openGameMenuLabel': 'Apri menu dei profili di gioco'
    },
    'pt': {
        'sourceGameLabel': 'Jogo atual',
        'targetGameLabel': 'Jogo de destino',
        'sourceDpiLabel': 'DPI atual',
        'targetDpiLabel': 'DPI de destino',
        'sensitivityLabel': 'Sensibilidade no jogo',
        'linkDpiLabel': 'Manter o mesmo DPI',
        'sourceStationLabel': 'Sua configuração atual',
        'targetStationLabel': 'Sua configuração de destino',
        'guideSourceText': 'Escolha seu jogo atual, insira o DPI e sua sensibilidade horizontal sem mirar.',
        'guideTargetText': 'Escolha o jogo de destino. Mantenha o DPI vinculado a menos que vá alterá-lo.',
        'guideResultText': 'Copie o resultado para o novo jogo e verifique uma volta completa de 360 graus.',
        'sourceInputHint': 'Encontre esses valores no software do mouse e no menu de opções do jogo.',
        'targetInputHint': 'O valor final aparece abaixo assim que a configuração for válida.',
        'profileResetText': 'Sensibilidade redefinida para um exemplo padrão. Substitua pelo seu valor real.',
        'resultForGameTemplate': '3. Insira este valor em {game}',
        'yawLabel': 'Escala yaw',
        'measuredProfileLabel': 'Perfil medido',
        'documentedProfileLabel': 'Perfil oficial',
        'targetSensitivityLabel': 'Insira esta sensibilidade',
        'copyResultLabel': 'Copiar resultado',
        'copiedLabel': 'Copiado',
        'swapLabel': 'Inverter conversão',
        'swapButtonLabel': 'Trocar',
        'shareLabel': 'Copiar link',
        'shareCopiedLabel': 'Link copiado',
        'presetsLabel': 'Ajustes de memória muscular',
        'presetFastLabel': 'Rápido 22 cm',
        'presetBalancedLabel': 'Equilibrado 34 cm',
        'presetControlLabel': 'Controle 50 cm',
        'cmUnitLabel': 'Métrico',
        'inchUnitLabel': 'Imperial',
        'physicalArcLabel': 'Giro de 360 graus',
        'sourceEdpiLabel': 'eDPI de origem',
        'targetEdpiLabel': 'eDPI de destino',
        'countsLabel': 'Pulsos do mouse',
        'matchQualityLabel': 'Confiança da conversão',
        'exactMathLabel': 'Constante yaw oficial',
        'calibrationLabel': 'Verificação física recomendada',
        'fastBandLabel': 'Órbita rápida',
        'balancedBandLabel': 'Órbita equilibrada',
        'controlBandLabel': 'Órbita de controle',
        'extendedBandLabel': 'Órbita estendida',
        'formulaLabel': 'Fórmula de conversão',
        'formulaText': 'sensibilidade destino = sensibilidade origem x DPI origem x yaw origem / (DPI destino x yaw destino)',
        'verificationTitle': 'Ajuste fino no mousepad',
        'verificationText': 'Coloque o mouse em uma marca no mousepad e faça uma volta completa de 360 graus em ambos os jogos.',
        'baseAimOnlyText': 'Conversão calculada apenas para tiro livre (hipfire).',
        'invalidInputText': 'Insira valores maiores que zero.',
        'openGameMenuLabel': 'Abrir menu de perfis de jogo'
    },
    'nl': {
        'sourceGameLabel': 'Huidige game',
        'targetGameLabel': 'Doelgame',
        'sourceDpiLabel': 'Huidige DPI',
        'targetDpiLabel': 'Doel DPI',
        'sensitivityLabel': 'Gevoeligheid in de game',
        'linkDpiLabel': 'Zelfde DPI behouden',
        'sourceStationLabel': 'Huidige opstelling',
        'targetStationLabel': 'Doelopstelling',
        'guideSourceText': 'Kies je huidige game, voer de DPI en horizontale gevoeligheid in.',
        'guideTargetText': 'Kies de doelgame. Laat DPI gekoppeld tenzij je deze verandert.',
        'guideResultText': 'Kopieer het resultaat naar de doelgame en controleer een 360 graden draai.',
        'sourceInputHint': 'Vind deze waarden in je muissoftware en spelinstellingen.',
        'targetInputHint': 'De doelwaarde verschijnt hieronder zodra de invoer geldig is.',
        'profileResetText': 'Gevoeligheid gereset naar voorbeeldwaarde. Vervang deze door jouw waarde.',
        'resultForGameTemplate': '3. Voer deze waarde in in {game}',
        'yawLabel': 'Yaw-schaal',
        'measuredProfileLabel': 'Gemeten profiel',
        'documentedProfileLabel': 'Gedocumenteerd profiel',
        'targetSensitivityLabel': 'Voer deze gevoeligheid in',
        'copyResultLabel': 'Resultaat kopiëren',
        'copiedLabel': 'Gekopieerd',
        'swapLabel': 'Omrekening omkeren',
        'swapButtonLabel': 'Wisselen',
        'shareLabel': 'Link kopiëren',
        'shareCopiedLabel': 'Link gekopieerd',
        'presetsLabel': 'Voorkeursinstellingen',
        'presetFastLabel': 'Snel 22 cm',
        'presetBalancedLabel': 'Gebalanceerd 34 cm',
        'presetControlLabel': 'Controle 50 cm',
        'cmUnitLabel': 'Metrisch',
        'inchUnitLabel': 'Imperiaal',
        'physicalArcLabel': 'Een volledige draai',
        'sourceEdpiLabel': 'Bron eDPI',
        'targetEdpiLabel': 'Doel eDPI',
        'countsLabel': 'Muispulsen',
        'matchQualityLabel': 'Profielnauwkeurigheid',
        'exactMathLabel': 'Exacte Yaw-waarde',
        'calibrationLabel': 'Fysieke controle aanbevolen',
        'fastBandLabel': 'Snelle zone',
        'balancedBandLabel': 'Gebalanceerde zone',
        'controlBandLabel': 'Controlezone',
        'extendedBandLabel': 'Uitgebreide zone',
        'formulaLabel': 'Omrekenformule',
        'formulaText': 'doelgevoeligheid = brongevoeligheid x bron DPI x bron yaw / (doel DPI x doel yaw)',
        'verificationTitle': 'Kalibratie voltooien',
        'verificationText': 'Markeer een startpunt op je muismat en maak een 360 graden draai in beide games.',
        'baseAimOnlyText': 'Alleen voor basis-hipfire horizontaal.',
        'invalidInputText': 'Voer positieve waarden in.',
        'openGameMenuLabel': 'Gameprofielmenu openen'
    },
    'pl': {
        'sourceGameLabel': 'Obecna gra',
        'targetGameLabel': 'Docelowa gra',
        'sourceDpiLabel': 'Obecne DPI',
        'targetDpiLabel': 'Docelowe DPI',
        'sensitivityLabel': 'Czułość w grze',
        'linkDpiLabel': 'Zachowaj to samo DPI',
        'sourceStationLabel': 'Obecna konfiguracja',
        'targetStationLabel': 'Docelowa konfiguracja',
        'guideSourceText': 'Wybierz grę, w którą grasz, wpisz DPI oraz czułość poziomą bez celowania.',
        'guideTargetText': 'Wybierz grę docelową. Pozostaw DPI połączone, chyba że je zmieniasz.',
        'guideResultText': 'Skopiuj wynik do nowej gry i sprawdź pełny obrót o 360 stopni.',
        'sourceInputHint': 'Znajdź te wartości w oprogramowaniu myszy i ustawieniach gry.',
        'targetInputHint': 'Wynik docelowy pojawi się poniżej po wpisaniu poprawnych danych.',
        'profileResetText': 'Czułość zresetowana do wartości przykładowej. Wpisz swoją wartość.',
        'resultForGameTemplate': '3. Wpisz tę wartość w {game}',
        'yawLabel': 'Skala yaw',
        'measuredProfileLabel': 'Zmierzony profil',
        'documentedProfileLabel': 'Oficjalny profil',
        'targetSensitivityLabel': 'Wpisz tę czułość',
        'copyResultLabel': 'Kopiuj wynik',
        'copiedLabel': 'Skopiowano',
        'swapLabel': 'Odwróć przeliczenie',
        'swapButtonLabel': 'Zamień',
        'shareLabel': 'Kopiuj link',
        'shareCopiedLabel': 'Link skopiowany',
        'presetsLabel': 'Ustawienia pamięci mięśniowej',
        'presetFastLabel': 'Szybki 22 cm',
        'presetBalancedLabel': 'Zrównoważony 34 cm',
        'presetControlLabel': 'Kontrola 50 cm',
        'cmUnitLabel': 'Metryczne',
        'inchUnitLabel': 'Calowe',
        'physicalArcLabel': 'Pełny obrót 360 stopni',
        'sourceEdpiLabel': 'Źródłowe eDPI',
        'targetEdpiLabel': 'Docelowe eDPI',
        'countsLabel': 'Impulsy myszy',
        'matchQualityLabel': 'Dokładność profilu',
        'exactMathLabel': 'Oficjalny stały wskaźnik yaw',
        'calibrationLabel': 'Zalecane sprawdzanie fizyczne',
        'fastBandLabel': 'Szybka strefa',
        'balancedBandLabel': 'Zrównoważona strefa',
        'controlBandLabel': 'Strefa kontroli',
        'extendedBandLabel': 'Rozszerzona strefa',
        'formulaLabel': 'Wzór przeliczenia',
        'formulaText': 'czułość docelowa = czułość źródłowa x DPI źródłowe x yaw źródłowe / (DPI docelowe x yaw docelowe)',
        'verificationTitle': 'Sprawdzenie na podkładce',
        'verificationText': 'Zaznacz punkt startowy na podkładce i wykonaj pełny obrót o 360 stopni w obu grach.',
        'baseAimOnlyText': 'Wyłącznie dla strzelania z biodra (hipfire).',
        'invalidInputText': 'Wpisz wartości dodatnie.',
        'openGameMenuLabel': 'Otwórz menu profili gier'
    },
    'id': {
        'sourceGameLabel': 'Game saat ini',
        'targetGameLabel': 'Game tujuan',
        'sourceDpiLabel': 'DPI saat ini',
        'targetDpiLabel': 'DPI tujuan',
        'sensitivityLabel': 'Sensitivitas dalam game',
        'linkDpiLabel': 'Pertahankan DPI yang sama',
        'sourceStationLabel': 'Pengaturan saat ini',
        'targetStationLabel': 'Pengaturan tujuan',
        'guideSourceText': 'Pilih game Anda saat ini, lalu masukkan DPI dan sensitivitas horizontal.',
        'guideTargetText': 'Pilih game tujuan. Biarkan DPI terhubung kecuali Anda mengubahnya.',
        'guideResultText': 'Salin hasil ke game tujuan dan verifikasi satu putaran penuh 360 derajat.',
        'sourceInputHint': 'Temukan nilai ini di perangkat lunak mouse dan pengaturan game Anda.',
        'targetInputHint': 'Nilai tujuan muncul di bawah setelah input valid.',
        'profileResetText': 'Sensitivitas diatur ulang ke contoh standar. Ganti dengan nilai asli Anda.',
        'resultForGameTemplate': '3. Masukkan nilai ini di {game}',
        'yawLabel': 'Skala yaw',
        'measuredProfileLabel': 'Profil terukur',
        'documentedProfileLabel': 'Profil resmi',
        'targetSensitivityLabel': 'Masukkan sensitivitas ini',
        'copyResultLabel': 'Salin hasil',
        'copiedLabel': 'Tersalin',
        'swapLabel': 'Balikkan konversi',
        'swapButtonLabel': 'Tukar',
        'shareLabel': 'Salin tautan',
        'shareCopiedLabel': 'Tautan tersalin',
        'presetsLabel': 'Preset memori otot',
        'presetFastLabel': 'Cepat 22 cm',
        'presetBalancedLabel': 'Seimbang 34 cm',
        'presetControlLabel': 'Kontrol 50 cm',
        'cmUnitLabel': 'Metrik',
        'inchUnitLabel': 'Imperial',
        'physicalArcLabel': 'Satu putaran penuh',
        'sourceEdpiLabel': 'eDPI asal',
        'targetEdpiLabel': 'eDPI tujuan',
        'countsLabel': 'Pulsa mouse',
        'matchQualityLabel': 'Akurasi profil',
        'exactMathLabel': 'Nilai yaw resmi',
        'calibrationLabel': 'Pemeriksaan fisik disarankan',
        'fastBandLabel': 'Zona cepat',
        'balancedBandLabel': 'Zona seimbang',
        'controlBandLabel': 'Zona kontrol',
        'extendedBandLabel': 'Zona diperluas',
        'formulaLabel': 'Rumus konversi',
        'formulaText': 'sensitivitas tujuan = sensitivitas asal x DPI asal x yaw asal / (DPI tujuan x yaw tujuan)',
        'verificationTitle': 'Pemeriksaan pada mousepad',
        'verificationText': 'Tandai titik awal di mousepad dan lakukan satu putaran 360 derajat di kedua game.',
        'baseAimOnlyText': 'Hanya untuk tembakan dari pinggul (hipfire).',
        'invalidInputText': 'Masukkan nilai positif.',
        'openGameMenuLabel': 'Buka menu profil game'
    },
    'sv': {
        'sourceGameLabel': 'Nuvarande spel',
        'targetGameLabel': 'Målspel',
        'sourceDpiLabel': 'Nuvarande DPI',
        'targetDpiLabel': 'Mål-DPI',
        'sensitivityLabel': 'Sensitivitet i spelet',
        'linkDpiLabel': 'Behåll samma DPI',
        'sourceStationLabel': 'Nuvarande inställning',
        'targetStationLabel': 'Målinställning',
        'guideSourceText': 'Välj ditt nuvarande spel, ange DPI och din horisontella sensitivitet.',
        'guideTargetText': 'Välj målspel. Låt DPI vara länkad om du inte ändrar den.',
        'guideResultText': 'Kopiera resultatet till målspelet och kontrollera en 360-graders vridning.',
        'sourceInputHint': 'Hitta dessa värden i din musprogramvara och spelinställningar.',
        'targetInputHint': 'Målvärdet visas nedan så snart inmatningen är giltig.',
        'profileResetText': 'Sensitiviteten återställd till exempelvärde. Ersätt med ditt eget värde.',
        'resultForGameTemplate': '3. Ange detta värde i {game}',
        'yawLabel': 'Yaw-skala',
        'measuredProfileLabel': 'Uppmätt profil',
        'documentedProfileLabel': 'Dokumenterad profil',
        'targetSensitivityLabel': 'Ange denna sensitivitet',
        'copyResultLabel': 'Kopiera resultat',
        'copiedLabel': 'Kopierat',
        'swapLabel': 'Vänd omvandling',
        'swapButtonLabel': 'Växla',
        'shareLabel': 'Kopiera länk',
        'shareCopiedLabel': 'Länk kopierad',
        'presetsLabel': 'Snabbval för minne',
        'presetFastLabel': 'Snabb 22 cm',
        'presetBalancedLabel': 'Balanserad 34 cm',
        'presetControlLabel': 'Kontroll 50 cm',
        'cmUnitLabel': 'Metrisk',
        'inchUnitLabel': 'Imperial',
        'physicalArcLabel': 'En hel vridning',
        'sourceEdpiLabel': 'Käll-eDPI',
        'targetEdpiLabel': 'Mål-eDPI',
        'countsLabel': 'Musimpulser',
        'matchQualityLabel': 'Profilprecision',
        'exactMathLabel': 'Exakt Yaw-värde',
        'calibrationLabel': 'Fysisk kontroll rekommenderas',
        'fastBandLabel': 'Snabb zon',
        'balancedBandLabel': 'Balanserad zon',
        'controlBandLabel': 'Kontrollzon',
        'extendedBandLabel': 'Utökad zon',
        'formulaLabel': 'Omvandlingsformel',
        'formulaText': 'målsensitivitet = källsensitivitet x käll-DPI x käll-yaw / (mål-DPI x mål-yaw)',
        'verificationTitle': 'Slutför kalibrering',
        'verificationText': 'Markera en startpunkt på musmattan och gör en 360-graders vridning i båda spelen.',
        'baseAimOnlyText': 'Endast för bas-hipfire horisontellt.',
        'invalidInputText': 'Ange positiva värden.',
        'openGameMenuLabel': 'Öppna spelprofilmeny'
    },
    'tr': {
        'sourceGameLabel': 'Mevcut oyun',
        'targetGameLabel': 'Hedef oyun',
        'sourceDpiLabel': 'Mevcut DPI',
        'targetDpiLabel': 'Hedef DPI',
        'sensitivityLabel': 'Oyun içi hassasiyet',
        'linkDpiLabel': 'Aynı DPI değerini koru',
        'sourceStationLabel': 'Mevcut kurulum',
        'targetStationLabel': 'Hedef kurulum',
        'guideSourceText': 'Oynadığınız oyunu seçin, DPI ve yatay hassasiyetinizi girin.',
        'guideTargetText': 'Hedef oyunu seçin. DPI değiştirmeyecekseniz bağlı bırakın.',
        'guideResultText': 'Sonucu hedef oyuna kopyalayın ve 360 derecelik dönüşü doğrulayın.',
        'sourceInputHint': 'Bu değerleri fare yazılımınızda ve oyun ayarlarında bulabilirsiniz.',
        'targetInputHint': 'Hedef değer geçerli giriş yapıldığında aşağıda görünür.',
        'profileResetText': 'Hassasiyet varsayılan örneğe sıfırlandı. Kendi değerinizle değiştirin.',
        'resultForGameTemplate': '3. Bu değeri {game} oyununa girin',
        'yawLabel': 'Yaw ölçeği',
        'measuredProfileLabel': 'Ölçülen profil',
        'documentedProfileLabel': 'Resmi profil',
        'targetSensitivityLabel': 'Bu hassasiyeti girin',
        'copyResultLabel': 'Sonucu kopyala',
        'copiedLabel': 'Kopyalandı',
        'swapLabel': 'Dönüştürmeyi tersine çevir',
        'swapButtonLabel': 'Değiştir',
        'shareLabel': 'Bağlantıyı kopyala',
        'shareCopiedLabel': 'Bağlantı kopyalandı',
        'presetsLabel': 'Kas hafızası ayarları',
        'presetFastLabel': 'Hızlı 22 cm',
        'presetBalancedLabel': 'Dengeli 34 cm',
        'presetControlLabel': 'Kontrol 50 cm',
        'cmUnitLabel': 'Metrik',
        'inchUnitLabel': 'İngiliz',
        'physicalArcLabel': 'Tam bir dönüş',
        'sourceEdpiLabel': 'Kaynak eDPI',
        'targetEdpiLabel': 'Hedef eDPI',
        'countsLabel': 'Fare vuruşları',
        'matchQualityLabel': 'Profil doğruluğu',
        'exactMathLabel': 'Resmi Yaw sabiti',
        'calibrationLabel': 'Fiziksel kontrol önerilir',
        'fastBandLabel': 'Hızlı bölge',
        'balancedBandLabel': 'Dengeli bölge',
        'controlBandLabel': 'Kontrol bölgesi',
        'extendedBandLabel': 'Genişletilmiş bölge',
        'formulaLabel': 'Dönüştürme formülü',
        'formulaText': 'hedef hassasiyet = kaynak hassasiyet x kaynak DPI x kaynak yaw / (hedef DPI x hedef yaw)',
        'verificationTitle': 'Mousepad üzerinde doğrulama',
        'verificationText': 'Mousepad üzerine bir başlangıç noktası koyun ve her iki oyunda da 360 derecelik bir dönüş yapın.',
        'baseAimOnlyText': 'Yalnızca kalçadan atış (hipfire) içindir.',
        'invalidInputText': 'Pozitif değerler girin.',
        'openGameMenuLabel': 'Oyun profili menüsünü aç'
    },
    'es': {
        'swapButtonLabel': 'Intercambiar'
    },
    'en': {
        'swapButtonLabel': 'Swap'
    },
    'ru': {
        'swapButtonLabel': 'Поменять'
    },
    'ja': {
        'swapButtonLabel': '入れ替え'
    },
    'ko': {
        'swapButtonLabel': '맞바꾸기'
    },
    'zh': {
        'swapButtonLabel': '對調'
    }
}

base_dir = r'd:\code\jjlmoya-utils-games\src\tool\mouse-sensitivity-converter\i18n'

for lang, ui_updates in locales.items():
    path = os.path.join(base_dir, f'{lang}.ts')
    with open(path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    for key, val in ui_updates.items():
        lines = content.splitlines()
        new_lines = []
        for line in lines:
            if f'"{key}"' in line or f"'{key}'" in line or f"{key}:" in line:
                indent = line[:line.find(key)]
                comma = ',' if line.strip().endswith(',') else ''
                if '"' in line:
                    new_lines.append(f'{indent}"{key}": "{val}"{comma}')
                else:
                    new_lines.append(f"{indent}{key}: '{val}'{comma}")
            else:
                new_lines.append(line)
        content = '\n'.join(new_lines)
    
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content + '\n')

print('Refreshed all 15 native UI translations with concise single-word swap buttons!')
